name: 🐛 Bug Report
title: "[Bug] "
description: Report a bug to help us reproduce and fix it.
labels: [ "bug" ]
assignees: [ "11101171" ]
body:
  - type: markdown
    attributes:
      value: |
        <img src="https://developer-pro.bitmart.com/images/logo-light@3x-caec722f.png" alt="BitMart logo" height="90px" align="right" />

        Thank you for finding the time to report the problem! We really appreciate the community efforts to improve BitMart SDK.

        #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/bitmartexchange/bitmart-python-sdk-api/issues).

  - type: dropdown
    attributes:
      label: Module Selection
      description: |
        Selecting a module makes it easier to locate problems
      multiple: false
      options:
        - "Http"
        - "Websocket"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Describe the Bug
      description:  |
        Please describe the bug clearly and concisely, preferably with code that reproduces the bug. Code snippets should be as concise as possible, and please take the time to remove irrelevant code to help us debug effectively. We hope that you can get the same results as you by copying the code and running it, so please avoid any external data or include related imports, etc.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: others
    attributes:
      label: Additional Supplementary Information
      description: |
        If you have anything else to add, please write it here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: >
        Thanks for your contribution 🎉!
   
 
